#!/bin/sh

# This script should contain the command(s) nessesary to switch off the nVidia card.

acpi_call () {
	echo "$*" > /proc/acpi/call
	result=$(cat /proc/acpi/call)
	case "$result" in
	    failed)
		echo "acpi_call $* failed."
		final=$(( $final & 0 ))
		;;
	    ok)
		echo "acpi_call $* succeded."
		final=$(( $final & 1 ))
		;;
	esac
}

rmmod nvidia

if lsmod | grep -q nvidia; then
	echo "Error: could not unload nvidia module, leaving card turned on." 1>&2
	exit 1
fi

modprobe acpi_call

if ! lsmod | grep -q acpi_call; then
	echo "Error: acpi_call module not loaded." 1>&2
	exit 1
fi

final=1

# Replace these command strings depending on your laptop model.
acpi_call "\_SB.PCI0.LPCB.EC0.TSDS"
acpi_call "\_SB.PCI0.PEGR.GFX0.DOFF"

if [ $final = 1 ]; then
	echo "Disabling nVidia card succeded."
	exit 0
else
	echo "Disabling nVidia card failed."
	exit 1
fi
