#!/bin/sh

# This script should contain the command(s) necessary to switch on the nVidia card.

acpi_call () {
	echo "$*" > /proc/acpi/call
	result=$(cat /proc/acpi/call)
	case "$result" in
		failed) echo "acpi_call $* failed." 1>&2 ;;
		ok) if [ "$OPT_VERBOSE" = "yes" ]; then echo "acpi_call $* succeded."; fi ;;
		*) if [ "$OPT_VERBOSE" = "yes" ]; then echo "acpi_call $* returned $result."; fi ;;
	esac
}

modprobe acpi_call

if ! lsmod | grep -q acpi_call; then
	echo "Error: acpi_call module not loaded." 1>&2
	exit 1
fi

# Replace this command string depending on your laptop model.
# This one works only for ASUS K53SJ.
acpi_call "\_SB.PCI0.PEGR.GFX0._PS0"

modprobe nvidia

if lsmod | grep -q nvidia; then
	echo "Enabling nVidia card succeded."
	exit 0
else
	echo "Enabling nVidia card failed."
	exit 1
fi
