#!/bin/sh

### BEGIN INIT INFO
# Provides:          debumblebee
# Required-Start:    nvidia-kernel
# Required-Stop:
# Should-Start:      kdm gdm
# Should-Stop:       kdm gdm
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: debumblebee initscript
# Description:       debumblebee initscript for Optimus graphics support
### END INIT INFO

# Author: Igor Urazov <z0rc3r@gmail.com>

if [ -r /etc/default/debumblebee ]; then
	. /etc/default/debumblebee
else
	VGL_DISPLAY=:8
fi

PATH=/sbin:/usr/local/sbin:/usr/sbin:/bin:/usr/local/bin:/usr/bin
LD_LIBRARY_PATH=/usr/lib/`dpkg-architecture -qDEB_HOST_MULTIARCH`/nvidia
DESC="Optimus X server"
NAME=debumblebee
DAEMON=/usr/bin/X
DAEMON_ARGS="-config /etc/X11/xorg.conf.nvidia -modulepath /usr/local/lib/debumblebee,/usr/lib/xorg/modules -sharevts $VGL_DISPLAY"
PIDFILE=/tmp/.X${VGL_DISPLAY#?}-lock
SCRIPTNAME=/etc/init.d/$NAME

. /lib/lsb/init-functions

do_start()
{
	! ps -p `cat $PIDFILE 2>&1` > /dev/null 2>&1 || return 1
	start-stop-daemon --start --quiet --background --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
	return 0
}

do_stop()
{
	kill `cat $PIDFILE 2>&1` > /dev/null 2>&1
	RETVAL=$?
	rm -f $PIDFILE
	return $RETVAL
}

case $1 in
  start)
	if [ "$ON_DEMAND" = "yes" ]; then
		if [ "$POWER_SAVE" = "yes" -a -x "$DISABLECARD" ]; then
			log_daemon_msg "Disabling nVidia card. POWER_SAVE option is enabled" "$NAME"
			log_end_msg 0
			OPT_VERBOSE=$VERBOSE $DISABLECARD
			exit 0
		else
			log_daemon_msg "Not starting $DESC. ON_DEMAND option is enabled" "$NAME"
			log_end_msg 0
			exit 0
		fi
	fi
	log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case $? in
		0) log_end_msg 0 ;;
		1) log_action_end_msg 1 "already running" ;;
	esac
	;;
  stop)
	if [ "$ON_DEMAND" = "yes" -a "$POWER_SAVE" = "yes" -a -x "$ENABLECARD" ]; then
		log_daemon_msg "Enabling nVidia card before shutdown" "$NAME"
		log_end_msg 0
		OPT_VERBOSE=$VERBOSE $ENABLECARD
	else
		log_daemon_msg "Stopping $DESC" "$NAME"
		do_stop
		case $? in
			0) log_end_msg 0 ;;
			2) log_action_end_msg 0 "already stopped" ;;
		esac
	fi
	;;
  demandon)
	if [ "$POWER_SAVE" = "yes" -a -x "$ENABLECARD" ]; then
		$ENABLECARD
	fi
	do_start ;;
  demandoff)
	do_stop
	if [ "$POWER_SAVE" = "yes" -a -x "$DISABLECARD" ]; then
		sleep 2
		$DISABLECARD
	fi
	;;
  status)
	status_of_proc -p $PIDFILE "$DAEMON" "$NAME" ;;
  restart)
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	do_start
	case $? in
		0) log_end_msg 0 ;;
		1) log_action_end_msg 1 "still running";;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart}" >&2
	exit 3
	;;
esac
