#!/bin/sh

### BEGIN INIT INFO
# Provides:          debumblebee
# Required-Start:    nvidia-kernel
# Required-Stop:
# Should-Start:      kdm gdm
# Should-Stop:       kdm gdm
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: debumblebee initscript
# Description:       debumblebee initscript for Optimus graphics support
### END INIT INFO

# Author: Igor Urazov <z0rc3r@gmail.com>

if [ -r /etc/default/debumblebee ]; then
	. /etc/default/debumblebee
fi

PATH=/sbin:/usr/local/sbin:/usr/sbin:/bin:/usr/local/bin:/usr/bin
LD_LIBRARY_PATH=/usr/lib/nvidia
DESC="Optimus X server"
NAME=debumblebee
DAEMON=/usr/bin/X
DAEMON_ARGS="-ac -config /etc/X11/xorg.conf.nvidia -sharevts -modulepath /usr/local/lib/debumblebee,/usr/lib/xorg/modules -nolisten tcp -noreset :1 vt8"
PIDFILE=/tmp/.X1-lock
SCRIPTNAME=/etc/init.d/$NAME

. /lib/lsb/init-functions

do_start()
{
	! ps -p `cat $PIDFILE 2>&1` > /dev/null 2>&1 || return 1
	start-stop-daemon --start --quiet --background --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
	return 0
}

do_stop()
{
	kill `cat $PIDFILE 2>&1` > /dev/null 2>&1
	RETVAL=$?
	rm -f $PIDFILE
	return $RETVAL
}

case $1 in
  start)
	if [ "$ON_DEMAND" = "yes" ]; then
		log_daemon_msg "Not starting $DESC. ON_DEMAND option is enabled" "$NAME"
		log_end_msg 0
		exit 0
	fi
	log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case $? in
		0) log_end_msg 0 ;;
		1) log_action_end_msg 1 "already running" ;;
	esac
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case $? in
		0) log_end_msg 0 ;;
		2) log_action_end_msg 0 "already stopped" ;;
	esac
	;;
  demandon)
	do_start ;;
  demandoff)
	do_stop ;;
  status)
	status_of_proc -p $PIDFILE "$DAEMON" "$NAME" ;;
  restart)
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	do_start
	case $? in
		0) log_end_msg 0 ;;
		1) log_action_end_msg 1 "still running";;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart}" >&2
	exit 3
	;;
esac
