#!/bin/sh

if [ -r /etc/default/debumblebee ]; then
	. /etc/default/debumblebee
else
	VGL_DISPLAY=:8
	VGL_COMPRESS=xv
	VGL_READBACK=pbo
	PIDFILE=/tmp/optirun.pid
fi

# Default options.
OPT_VERBOSE=$VERBOSE
OPT_HELP=false
OPT_READBACK=$VGL_READBACK
if [ $MODULE = nvidia ]; then
	OPT_LIB="/usr/lib/`dpkg-architecture -qDEB_HOST_MULTIARCH`/nvidia:/usr/lib32/nvidia"
elif [ $MODULE = nouveau ]; then
	OPT_LIB="/usr/lib/`dpkg-architecture -qDEB_HOST_MULTIARCH`:/usr/lib32"
else
	echo "Error: unknown MODULE option." 1>&2
fi

# Parsing command line.
if [ $# -eq 0 ]; then
	OPT_HELP=true
else
	while [ $# -gt 0 ]; do
		case "$1" in
			-h|-help|--help) OPT_HELP=true ;;
			-v|-verbose|--verbose) OPT_VERBOSE=yes ;;
			-r|-readback|--readback) shift;	OPT_READBACK=$1 ;;
			--) shift; break ;;
			*) break ;;
		esac
	shift
done
fi

# Show help when needed.
if $OPT_HELP; then
	echo "Usage: optirun [options] <application> [application arguments]\n"
	echo "optirun options list:"
	echo " -r|-readback|--readback <none|pbo|sync> : Override VGL_READBACK option. (default is \"$VGL_READBACK\")"
	echo " -v|-verbose|--verbose                   : Be verbose, show more technical inforation."
	echo " -h|-help|--help                         : Show this help."
	exit 0
fi

# Or be verbose if requested.
if [ "$OPT_VERBOSE" = "yes" ]; then
	export OPT_VERBOSE=$OPT_VERBOSE
	VGL_VERBOSE="+v"
fi

export VGL_READBACK=$OPT_READBACK

if [ "$ON_DEMAND" = "yes" ]; then
# Checking pids from pidfile.
# If pid doesn't belong to other optirun instance then remove it from file.
	if [ -e $PIDFILE ]; then
		cat $PIDFILE | while read pid; do
			if [ -n $pid ]; then
				if ! ps -p $pid | grep -q optirun; then
					sed -i '/'$pid'/d' $PIDFILE
				fi
			fi
		done
	fi
# If pidfile is empty or missing, then there is no other optirun instances running.
# So we need to start X server for nVidia card.
	if [ ! -s $PIDFILE ]; then
		sudo /etc/init.d/debumblebee demandon
	fi
# Check that X server is running.
	sleep 1
	if ! /etc/init.d/debumblebee status > /dev/null; then
		echo "Error: debumblebee service was not able to start." 1>&2
		echo "Actually this means that launch of X server for nVidia card failed for some reason." 1>&2
		echo "You may check the log at /var/log/Xorg.${VGL_DISPLAY#?}.log" 1>&2
# We need to make sure that card is disabled at the end even if we failed to start.
		sudo /etc/init.d/debumblebee demandoff
		exit 1
	fi
# Adding current pid to pidfile.
	echo $$ >> $PIDFILE
fi

# Execute heardbeat command every 30 seconds to prevent screensaver launch.
if [ "$DISABLE_SCREENSAVER" = "yes" ]; then
	sh -c "while : ; do $HEARTBEAT_CMD ; sleep 30; done" &
	trap "kill $!" INT TERM EXIT
fi

# Launch selected application through VirtualGL using 32 or 64 bit shared libs.
vglrun $VGL_VERBOSE -c $VGL_COMPRESS -d $VGL_DISPLAY -ld $OPT_LIB "$@"

# Removing current pid from pidfile
if [ "$ON_DEMAND" = "yes" ]; then
	sed -i '/'$$'/d' $PIDFILE
# If pidfile is empty, then there is no other optirun instances running.
# So we need to stop X server for nVidia card.
	if [ ! -s $PIDFILE ]; then
		rm -f $PIDFILE
		sudo /etc/init.d/debumblebee demandoff
	fi
fi

exit 0
