#!/bin/sh

# Function for launch VirtualGL client with particular compression options.
# Otherwise vlgrun won't be able to work.
vglclient_start () {
if [ "$1" = "jpeg" -o "$1" = "rgb" -o "$1" = "yuv" ]; then
	if [ "$2" = "yes" ]; then
		vglclient -gl -detach
	else
		vglclient -gl -detach -l /dev/null 1>/dev/null 2>&1
	fi
fi
}

# Also we need to kill vglclient sometimes, doh.
vglclient_stop () {
	if [ "$1" = "jpeg" -o "$1" = "rgb" -o "$1" = "yuv" ]; then
		if [ "$2" = "yes" ]; then
			vglclient -kill
		else
			vglclient -kill 1>/dev/null 2>&1
		fi
	fi
}

if [ -r /etc/default/debumblebee ]; then
	. /etc/default/debumblebee
else
	VGL_DISPLAY=:8
	VGL_COMPRESS=xv
	VGL_READBACK=pbo
	PIDFILE=/tmp/optirun.pid
fi

# Default options.
OPT_VERBOSE=$VERBOSE
OPT_HELP=false
OPT_READBACK=$VGL_READBACK
OPT_COMPRESS=$VGL_COMPRESS

# Parsing command line.
if [ $# -eq 0 ]; then
	OPT_HELP=true
else
	while [ $# -gt 0 ]; do
		case "$1" in
			-h|-help|--help) OPT_HELP=true ;;
			-v|-verbose|--verbose) OPT_VERBOSE=yes ;;
			-r|-readback|--readback) shift; OPT_READBACK=$1 ;;
			-c|-compress|--compress) shift; OPT_COMPRESS=$1 ;;
			--) shift; break ;;
			*) break ;;
		esac
	shift
done
fi

# Show help when needed.
if $OPT_HELP; then
	echo "Usage: optirun [options] <application> [application arguments]\n"
	echo "optirun options list:"
	echo " -r|-readback|--readback <none|pbo|sync> : Override VGL_READBACK option. (default is \"$VGL_READBACK\")"
	echo " -c|-compress|--compress <proxy|jpeg|xv| : Override VGL_COMPRESS option. (default is \"$VGL_COMPRESS\")"
	echo "                          rgb|yuv>"
	echo " -v|-verbose|--verbose                   : Be verbose, show more technical inforation."
	echo " -h|-help|--help                         : Show this help."
	exit 0
fi

# Check for valid module option and set special LD path for nvidia
if [ "$MODULE" = "nvidia" ]; then
	OPT_LIB="/usr/lib/`dpkg-architecture -qDEB_HOST_MULTIARCH`/nvidia:/usr/lib32/nvidia"
elif [ "$MODULE" != "nouveau" ]; then
	echo "Error: unknown MODULE option." 1>&2
	exit 1
fi

# Be verbose if requested.
if [ "$OPT_VERBOSE" = "yes" ]; then
	export OPT_VERBOSE=$OPT_VERBOSE
	VGL_VERBOSE="+v"
fi

# Export readback mode for vgl
export VGL_READBACK=$OPT_READBACK

if [ "$ON_DEMAND" = "yes" ]; then
# Checking pids from pidfile.
# If pid doesn't belong to other optirun instance then remove it from file.
	if [ -e $PIDFILE ]; then
		cat $PIDFILE | while read pid; do
			if [ -n $pid ]; then
				if ! ps -p $pid | grep -q optirun; then
					sed -i '/'$pid'/d' $PIDFILE
				fi
			fi
		done
	fi
# If pidfile is empty or missing, then there is no other optirun instances running.
# So we need to start X server for nVidia card and sometimes vglclient.
	if [ ! -s $PIDFILE ]; then
		sudo /etc/init.d/debumblebee demandon
		vglclient_start $OPT_COMPRESS $OPT_VERBOSE
	fi
# Check that X server is running.
	sleep 1
	if ! /etc/init.d/debumblebee status > /dev/null; then
		echo "Error: debumblebee service was not able to start." 1>&2
		echo "Actually this means that launch of X server for nVidia card failed for some reason." 1>&2
		echo "You may check the log at /var/log/Xorg.${VGL_DISPLAY#?}.log" 1>&2
		vglclient_stop $OPT_COMPRESS $OPT_VERBOSE
# We need to make sure that card is disabled at the end even if we failed to start.
		sudo /etc/init.d/debumblebee demandoff
		exit 1
	fi
# Adding current pid to pidfile.
	echo $$ >> $PIDFILE
fi

# Execute heardbeat command every 30 seconds to prevent screensaver launch.
if [ "$DISABLE_SCREENSAVER" = "yes" ]; then
	sh -c "while : ; do $HEARTBEAT_CMD ; sleep 30; done" &
	trap "kill $!" INT TERM EXIT
fi

# Always start vglclient at this case
if [ "$ON_DEMAND" = "no" ]; then
	vglclient_start $OPT_COMPRESS $OPT_VERBOSE
fi

# Launch selected application through VirtualGL using 32 or 64 bit shared libs.
vglrun $VGL_VERBOSE -c $OPT_COMPRESS -d $VGL_DISPLAY -ld $OPT_LIB "$@"

# And always kill it too.
if [ "$ON_DEMAND" = "no" ]; then
	vglclient_stop $OPT_COMPRESS $OPT_VERBOSE
fi

# Removing current pid from pidfile
if [ "$ON_DEMAND" = "yes" ]; then
	sed -i '/'$$'/d' $PIDFILE
# If pidfile is empty, then there is no other optirun instances running.
# So we need to stop X server for nVidia card and vglclient.
	if [ ! -s $PIDFILE ]; then
		rm -f $PIDFILE
		vglclient_stop $OPT_COMPRESS $OPT_VERBOSE
		sudo /etc/init.d/debumblebee demandoff
	fi
fi

exit 0
